<a href="https://colab.research.google.com/github/anniechooimh/Hospitality-Analytics/blob/main/Capstone_Hospitality%20Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

#import the five datasets

booking = pd.read_csv("https://raw.githubusercontent.com/anniechooimh/Hospitality-Analytics/refs/heads/main/Bookings.csv")
customer = pd.read_csv("https://raw.githubusercontent.com/anniechooimh/Hospitality-Analytics/refs/heads/main/Customer%20Types.csv")
hotel = pd.read_csv("https://raw.githubusercontent.com/anniechooimh/Hospitality-Analytics/refs/heads/main/Hotels.csv")
market = pd.read_csv("https://raw.githubusercontent.com/anniechooimh/Hospitality-Analytics/refs/heads/main/Market%20Segments.csv")
status = pd.read_csv("https://raw.githubusercontent.com/anniechooimh/Hospitality-Analytics/refs/heads/main/Reservation%20Status.csv")

display(booking.head())
display(customer.head())
display(hotel.head())
display(market.head())
display(status.head())

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,1,1,1,1,1,0,342,2015,July,27,...,0,0,3,NaN,NaN,0,0.0,0,0,2015-07-01
1,2,1,1,1,1,0,737,2015,July,27,...,0,0,4,NaN,NaN,0,0.0,0,0,2015-07-01
2,3,1,1,1,1,0,7,2015,July,27,...,0,0,0,NaN,NaN,0,75.0,0,0,2015-07-02
3,4,1,2,1,1,0,13,2015,July,27,...,0,0,0,304.0,NaN,0,75.0,0,0,2015-07-02
4,5,1,3,1,1,0,14,2015,July,27,...,0,0,0,240.0,NaN,0,98.0,0,1,2015-07-03

   Customer_Type_ID customer_type deposit_type meal
0                 1     Transient   No Deposit   BB
1                 2     Transient   No Deposit   FB
2                 3     Transient   No Deposit   HB
3                 4      Contract   No Deposit   BB
4                 5      Contract   No Deposit   HB

   Hotel_ID         hotel
0         1  Resort Hotel
1         2    City Hotel

   Market_Segment_ID market_segment distribution_channel
0                  1         Direct               Direct
1                  2      Corporate            Corporate
2                  3      Online TA                TA/TO
3                  4  Offline TA/TO                TA/TO
4                  5  Complementary               Direct

   Reservation_ID reservation_status
0               1          Check-Out
1               2           Canceled
2               3            No-Show

Data Cleansing and Preparation

Review data profile and identify missing values, handle empty rows, correct data types to prepare the data for analysis.

In [12]:
#Identify columns with missing values on the booking dataset

booking.info()
booking.isnull().sum()

#Clean missing null values

#Children - blank replace with zero (0) value
#Country -
#Agent and Company columns - remove as they are agent/company identifier which are applicable in this analysis
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  int64
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119386 non-null  float64
 15  babies                          119390 non-null  int64
 16  country                         118902 non-null  object
 17  is_repeated_guest               119390 non-null  int64
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           103050 non-null  float64
 22  company                         6797 non-null    float64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(21), object(3)
memory usage: 25.5+ MB

Booking_ID                             0
Hotel_ID                               0
Market_Segment_ID                      0
Customer_Type_ID                       0
Reservation_ID                         0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
country                              488
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
booking_changes                        0
agent                              16340
company                           112593
days_in_waiting_list                   0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status_date                0
dtype: int64